workflows:
  flet-android-build:
    name: Build Alexandra APK
    max_build_duration: 20
    instance_type: mac_mini_m1
    environment:
      vars:
        FLET_PROJECT_DIR: "final"
    triggering:
      events:
        - push
    scripts:
      - name: Set up Python environment
        script: |
          pip install --upgrade pip
          pip install flet flet-cli
      - name: Build APK via Flet
        script: |
          cd final
          # Флаг --yes затыкает Flet, и он сам всё скачает без вопросов
          /Users/builder/.pyenv/versions/3.12.7/bin/flet build apk Alexandra.py --yes
    artifacts:
      - final/build/apk/*.apk
