name: Build Kivy APK with Buildozer

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

# Включаем поддержку Node 24 глобально для всего запуска
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Buildozer and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev lldd gperf textinfo libffi-dev autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libgomp1
        pip install --upgrade pip
        pip install buildozer cython

    - name: Initialize Buildozer
      run: buildozer init

    - name: Configure buildozer.spec
      run: |
        # Тюнингуем конфиг под наше приложение
        sed -i 's/^title =.*/title = AlexandraApp/' buildozer.spec
        sed -i 's/^package.name =.*/package.name = alexandraapp/' buildozer.spec
        sed -i 's/^package.domain =.*/package.domain = org.fara/' buildozer.spec
        sed -i 's/^source.include_exts =.*/source.include_exts = py,png,jpg,kv,atlas/' buildozer.spec
        sed -i 's/^requirements =.*/requirements = python3,kivy/' buildozer.spec
        # Насильно соглашаемся с лицензией SDK Google
        sed -i 's/^#android.accept_sdk_license =.*/android.accept_sdk_license = True/' buildozer.spec
        sed -i 's/^# android.accept_sdk_license =.*/android.accept_sdk_license = True/' buildozer.spec

    - name: Build APK with Buildozer
      # Разрешаем запуск от имени root, чтобы убрать ошибку 100
      run: buildozer -v android debug
      env:
        BUILDOZER_ALLOW_KIVY_NEW_DESIGN: 1
        BUILDOZER_WARN_ON_ROOT: 0

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Kivy-Android-APK
        path: .buildozer/android/platform/build-armeabi-v7a_arm64-v8a/dists/alexandraapp__armeabi-v7a_arm64-v8a/build/outputs/apk/debug/*.apk
